import Head from 'next/head';
import Footer from '../components/Footer';
import Merokok from '../components/BerhentiMerokok__main';
import Navbarku from '../components/Navbarku';

export default function BerhentiMerokok() {
  return (
    <div>
      <Head>
        <title>Berhenti Merokok</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <Merokok />
      <Footer />
    </div>
  );
}
