import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer';
import DaftarSelanjutnya from '../components/DaftarSelanjutnya';
import Navbarku from '../components/Navbarku';

export default function DaftarLanjut() {
  return (
    <div>
      <Head>
        <title>Daftar Selanjutnya</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <DaftarSelanjutnya />
      <Footer />
    </div>
  );
}
