import Head from 'next/head';
import Footer from '../components/Footer';
import KontenAnak from '../components/DBDdanTipes';
import Navbarku from '../components/Navbarku';

export default function DBDdanTipes() {
  return (
    <div>
      <Head>
        <title>DBD dan Tipes</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <KontenAnak />
      <Footer />
    </div>
  );
}
