import Head from 'next/head';
import Footer from '../components/Footer';
import InfoKesehatan__main from '../components/InfoKesehatan__main';
import Navbarku from '../components/Navbarku';

export default function InfoKesehatanUtama() {
  return (
    <div>
      <Head>
        <title>Info Kesehatan</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <InfoKesehatan__main />
      <Footer />
    </div>
  );
}
