import Head from 'next/head';
import Footer from '../components/Footer';
import Obe from '../components/Obesitas__main';
import Navbarku from '../components/Navbarku';

export default function Obesitas() {
  return (
    <div>
      <Head>
        <title>Obesitas</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <Obe />
      <Footer />
    </div>
  );
}
