import Head from 'next/head';
import Footer from '../components/Footer';
import PU from '../components/PoliUmum__main';
import Navbarku from '../components/Navbarku';

export default function PoliUmum() {
  return (
    <div>
      <Head>
        <title>Poli Umum</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <PU />
      <Footer />
    </div>
  );
}
