import Head from 'next/head';
import Footer from '../components/Footer';
import KIA from '../components/PoliKIA__main';
import Navbarku from '../components/Navbarku';

export default function PoliKIA() {
  return (
    <div>
      <Head>
        <title>Poli Kesehatan Ibu dan Anak</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <KIA />
      <Footer />
    </div>
  );
}
