import Head from 'next/head';
import Footer from '../components/Footer';
import Profil__main from '../components/Profil__main';
import Navbarku from '../components/Navbarku';

export default function ProfilUtama() {
  return (
    <div>
      <Head>
        <title>Profil</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <Profil__main />
      <Footer />
    </div>
  );
}
