import Head from 'next/head';
import Footer from '../components/Footer';
import Profil from '../components/Puskesmas__main';
import Navbarku from '../components/Navbarku';

export default function Puskesmas() {
  return (
    <div>
      <Head>
        <title>Profil Puskesmas</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <Profil />
      <Footer />
    </div>
  );
}
