import Head from 'next/head';
import Footer from '../components/Footer';
import TK from '../components/TentangKami__main';
import Navbarku from '../components/Navbarku';

export default function VisiMisi() {
  return (
    <div>
      <Head>
        <title>Tentang Kami</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <TK/>
      <Footer />
    </div>
  );
}
