import Head from 'next/head';
import Footer from '../components/Footer';
import AW from '../components/VisiMisi__main';
import Navbarku from '../components/Navbarku';

export default function VisiMisi() {
  return (
    <div>
      <Head>
        <title>Visi Misi</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbarku />
      <AW />
      <Footer />
    </div>
  );
}
